<?php
/*
 *
 * This file is generated programmatically.
 * Any manual changes will be overwritten.
 *
 */
date_default_timezone_set('America/Chicago');
define('GLOBAL_APP_PATH', "/usr/local/dataloader/");
define('GLOBAL_PID_DIRECTORY', "/var/run/dataloader/");
define('GLOBAL_LOG_DIRECTORY', "/usr/local/dataloader/logs/");
define('GLOBAL_DATABASE_DIRECTORY', "/disk1/mysql/datafeeds/");
define('GLOBAL_ADMIN_EMAIL', "rvoelker@localhost");
define('GLOBAL_PATH_TO_COPY_COMMAND', "/bin/cp");
define('GLOBAL_PATH_TO_MOVE_COMMAND', "/bin/mv");
define('GLOBAL_PATH_TO_KILL_COMMAND', "/bin/kill");
define('GLOBAL_PATH_TO_INDEXER', "/usr/local/bin/indexer");
define('DATABASE_HOST', "localhost");
define('DATABASE_NAME', "datafeeds");
define('DATABASE_USER', "rvoelker");
define('DATABASE_PASSWORD', "rv99105");
define('LOG_LEVEL', 11);
define('LEVEL_CRITICAL', 1);
define('LEVEL_FILE_OPERATION', 3);
define('LEVEL_PROGRAMMING_WARNING', 4);
define('LEVEL_DATA_WARNING', 5);
define('LEVEL_DATABASE_OPERATION', 6);
define('LEVEL_STATUS', 7);
define('LEVEL_INFORMATION', 8);
define('LEVEL_MINUTIA', 10);
define('LEVEL_DEBUG', 11);
define('DATALOADER_SAVE_COPIES_OF_FEEDS', true);
define('DATALOADER_MAX_FILESIZE_TO_COPY', 0);
define('DATALOADER_SLEEP_TIME', 5);
define('DATALOADER_PID_FILE', "dataloader.pid");
define('DATALOADER_PATH_TO_BACKEND_SPHINX_CONFIGURATION_FILE', "/usr/local/dataloader/sphinx.conf");
define('TEMPORARY_OUTFILE_PATH', "/disk1/mysql/datafeeds/al_01.sql");
define('DATALOADER_COMMISSIONJUNCTION_OUTFILE', "/disk1/mysql/datafeeds/commissionjunctionoutfile_dl.txt");
define('DATALOADER_LINKSHARE_OUTFILE', "/disk1/mysql/datafeeds/linkshareoutfile_dl.txt");
define('DATALOADER_PERFORMICS_OUTFILE', "/disk1/mysql/datafeeds/performicsoutfile_dl.txt");
define('LINKSHARE_CONFIG_FILE', "/usr/local/dataloader/linkshare_config.ini");
define('LINKSHARE_SECONDS_BETWEEN_FTP_LOGINS', 1800);
define('LINKSHARE_PID_FILE', "linkshare_monitor.pid");
define('LINKSHARE_FTP_HOST', "aftp.linksynergy.com");
define('LINKSHARE_FTP_USERNAME', "dealhunting");
define('LINKSHARE_FTP_PASSWORD', "Rolpv43Ln");
define('LINKSHARE_FTP_UPLOAD_PATH', "/usr/local/dataloader/upload_loc");
define('FEEDMAPPING_DO_NOT_REINDEX_FILENAME', "/usr/local/dataloader/run/do_not_reindex");
define('FEEDMAPPING_TEMPORARY_TABLE_PREFIX', "tmp_");
define('FEEDMAPPING_COMMISSIONJUNCTION_OUTFILE', "/disk1/mysql/datafeeds/commissionjunctionoutfile.txt");
define('FEEDMAPPING_LINKSHARE_OUTFILE', "/disk1/mysql/datafeeds/linkshareoutfile.txt");
define('FEEDMAPPING_PERFORMICS_OUTFILE', "/disk1/mysql/datafeeds/performicsoutfile.txt");
define('FEEDMAPPING_MAX_RECORDS_PER_BLOCK', 50000);
define('FEEDMAPPING_LOGFILE', "feedFieldMap.log");
define('FEEDMAPPING_SLEEP_TIME_WHEN_BLOCKED', 10);
define('FEEDMAPPING_PROCESS_NAME', "feedFieldMap");
define('FRONTEND_GENERATOR_LOGFILE', "fegenerator.log");
define('FRONTEND_SLEEP_TIME_BETWEEN_LOOPS', 120);
define('FRONTEND_SLEEP_TIME_AFTER_FILE_GENERATION', 24);
define('FRONTEND_READY_TO_TRANSFER_FILENAME', "ready_to_transfer");
define('SEARCHSITE_CONTROL_DIRECTORY', "/usr/local/dataloader/searchsite_dbcreation/");
define('SEARCHSITE_LOGFILE', "searchsiteFeedMap.log");
define('SEARCHSITE_DO_NOT_REINDEX_FILENAME', "/usr/local/dataloader/run/searchsite_do_not_reindex");
define('SEARCHSITE_DATABASE_ONE', "searchsiteone");
define('SEARCHSITE_DATABASE_TWO', "searchsitetwo");
define('SEARCHSITE_OUTFILE', "/disk1/mysql/datafeeds/searchsiteoutfile.txt");
define('SEARCHSITE_SPHINX_PORT', 3314);
define('SEARCHSITE_ONLINEDBNAME_FILE', "/disk1/mysql/datafeeds/searchsiteOnlineDatabase.txt");
define('SEARCHSITE_STATISTICS_DATABASE_NAME', "searchsite_stats");
define('SEARCHSITE_STATISTICS_DATABASE_HOST', "localhost");
define('SEARCHSITE_STATISTICS_DATABASE_USERNAME', "rvoelker");
define('SEARCHSITE_STATISTICS_DATABASE_PASSWORD', "rv99105");
define('IMAGECACHE_SERVER', "http://imageserver.dealhunting.com:7070");
define('IMAGECACHE_DATABASE_HOST', "localhost");
define('IMAGECACHE_DATABASE_USER', "rvoelker");
define('IMAGECACHE_DATABASE_PASSWORD', "rv99105");
define('IMAGECACHE_DATABASE_NAME', "datafeeds");
define('IMAGECACHE_DATABASE_LIST_TABLENAME', "chachedImages");
define('IMAGECACHE_OUTPUT_DIRECTORY', "/usr/local/www/imageserver.dealhunting.com/");
define('IMAGECACHE_NUMBER_OF_IMAGES_PER_CYCLE', "1000");
define('IMAGECACHE_TABLE_STATS', "stats_imagecache");
define('IMAGECACHE_LOG_FILE', "/usr/local/dataloader/imagecache.log");
define('IMAGECACHE_PID_FILE', "/var/run/dataloader/cacheImages.pid");
define('DEBUG', true);
define('FEEDMAPPING_PID_FILE', "feedFieldMap.pid");
define('ADMINPANEL_DEBUG', true);
define('ADMINPANEL_DATE_FIELD_FORMAT', "Y-n-j");
define('ADMINPANEL_DATEPICKER_DATE_FIELD_FORMAT', "format-y-m-d");
define('ADMINPANEL_DB_SERVER', "localhost");
define('ADMINPANEL_DB_NAME', "dh_newadmin");
define('ADMINPANEL_DB_USERNAME', "dealhuntingAdmin");
define('ADMINPANEL_DB_PASSWORD', "dh*K98_3#.&LRoBb");
define('ADMINPANEL_APP_PATH', "/usr/local/www/www.dealhunting.com/newadmin/");
define('ADMINPANEL_WEB_PATH', "/newadmin");
define('ADMINPANEL_VHOSTS_DIRECTORY', "/usr/local/etc/apache/vhosts");
define('ADMINPANEL_VHOSTS_DOCUMENT_ROOT', "/home/gcummins/dev/");
define('ADMINPANEL_MODULE_DIRECTORY', "modules");
define('ADMINPANEL_SUBSITES_TABLENAME', "subsites");
define('ADMINPANEL_SUBSITES_KEYWORDS_TABLENAME', "subsites_keywords");
define('ADMINPANEL_THEME', "");
define('ADMINPANEL_MENU_TYPE', "css");
define('ADMINPANEL_MODULES_ORDERBY', "db");
define('ADMINPANEL_MAX_TABLE_ROWS', 10);
define('ADMINPANEL_MAX_PAGINATION_LINKS', 10);
define('ADMINPANEL_URL_LENGTH', 100);
define('DEALHUNTING_GALLERY_LOCATION', "dhimages");
define('DEALHUNTING_GALLERY_FILESYSTEM_PATH', "/usr/local/www/www.dealhunting.com/dhimages/");
define('DEALHUNTING_DATAFEEDS_DATABASE', "datafeeds");
define('DEALHUNTING_SEARCHSITE_DATABASE', "datafeeds");
define('DEALHUNTING_BANNERS_TABLE', "banners");
define('DEALHUNTING_DB_NAME', "dealhunting");
define('DEALHUNTING_CATEGORIES_TABLE', "category");
define('DEALHUNTING_COMPANIES_TABLE', "company");
define('DEALHUNTING_COUPONS_TABLE', "coupon");
define('DEALHUNTING_REDIRECTION_TABLE', "redir");
define('DEALHUNTING_SEARCHTERMS_TABLE', "srchlog");
define('DEALHUNTING_STORECATEGORIES_TABLE', "storecat");
define('DEALHUNTING_TOPDEALS_TABLE', "topdeals_new");
define('DEALHUNTING_DAILYNOTES_TABLE', "dailynotes");
define('DEALHUNTING_DAILYDEALS_TABLE', "deals");
define('DEALHUNTING_FEED_TYPE_1', "CJ");
define('DEALHUNTING_FEED_TYPE_2', "LinkShare");
define('DEALHUNTING_FEED_TYPE_3', "Performics");
define('LANGUAGE_CREATE_CSV_FILE', "Create as CSV file");
define('ADMINPANEL_GROUPS_ADMINISTRATOR_ID', 1);
define('ADMINPANEL_GROUPS_USER_ID', 2);
define('LANGUAGE_ERROR_OPERATION_NOT_PERMITTED', "This operation is not permitted.");
define('LANGUAGE_VIEWED_MAIN_PAGE', "Viewed main page");
define('LANGUAGE_DELETE_OBJECT_ID', "Deleted %s with ID '%s'");
define('LANGUAGE_DELETE_OBJECT_NAME', "Deleted %s '%s'");
define('LANGUAGE_MODIFY_OBJECT_ID', "Modified %s with ID '%s'");
define('LANGUAGE_MODIFY_OBJECT_NAME', "Modified %s '%s'");
define('LANGUAGE_CREATE_OBJECT_ID', "Created %s with ID '%s'");
define('LANGUAGE_CREATE_OBJECT_NAME', "Created %s '%s'");
define('ADMINPANEL_AUDITLOG_MAX_LOG_TAG_LENGTH', 25);
define('ADMINPANEL_IMAGES_ACTION_EDIT', "/newadmin/images/edit.png");
define('ADMINPANEL_IMAGES_ACTION_DELETE', "/newadmin/images/delete.png");
define('ADMINPANEL_BANNER_DEFAULT_WIDTH', 468);
define('ADMINPANEL_BANNER_DEFAULT_HEIGHT', 60);
define('DEALHUNTING_DB_HOST', "localhost");
define('DEALHUNTING_DB_USERNAME', "rvoelker");
define('DEALHUNTING_DB_PASSWORD', "rv99105");
define('ADMINPANEL_NOTIFY_FATAL_ERROR', true);
define('ADMINPANEL_NOTIFY_NONFATAL_ERROR', true);
?>
